feature numpy provides : high performance multi-dimensional array object

In [1]:
import numpy as np

In [3]:
# create a basic numpy array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
# shape of array
a.shape

(3,)

In [5]:
#element access
print(a[0])
print(a[1])

1
2


In [6]:
# change the value
a[0] = 5
print(a[0])

5


In [10]:
# 2d array
b = np.array([[1,2,3],[4,5,6],[7,8,9],[0,1,2]])
print(b)
print(b.shape)
print(b[1])
print(b[1][1])

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 1 2]]
(4, 3)
[4 5 6]
5


In [11]:
# for float values
c = np.array([1.0,3.9,7.9])
print(c)
print(c.shape)
print(c[2])

[1.  3.9 7.9]
(3,)
7.9


Different ways of creating numpy arrays

In [15]:
x = np.zeros((3,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
y = np.ones((1,2))
print(y)

[[1. 1.]]


In [19]:
# print the array with specified value
z = np.full((2,3),7)
print(z)

[[7 7 7]
 [7 7 7]]


In [21]:
# random values in the array
r = np.random.random((4,5))
print(r)

[[0.1230662  0.90813256 0.49399422 0.51610328 0.51604257]
 [0.28019982 0.361479   0.32646898 0.54548597 0.49081287]
 [0.54054433 0.14137286 0.74270498 0.66107886 0.90849179]
 [0.22876835 0.64553362 0.07813849 0.09611083 0.47518231]]


Array indexing:

In [29]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

# slicing for 1 and 2 row and 2 & 3 column
b = a[:2,1:3]
print(b)

print(a[0,1])
b[0,0] = 75
print(b[0,0])
print(a[0,1])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
75
75
[[ 1 75  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Boolean array indexing: this indexing is used to check that satisfy some condition

In [33]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)

print(a>2)
# values which are greater than 2
print(a[a>2])

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


Basic math function on array

In [35]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [37]:
# addition
print(x+y)
print(np.add(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [38]:
# subtract
print(y-x)
print(np.subtract(y,x))

[[4 4]
 [4 4]]
[[4 4]
 [4 4]]


In [39]:
# multiply
print(x*y)
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [40]:
#divide
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [41]:
#modulo
print(x%y)
print(np.mod(x,y))

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [42]:
# sum
print(np.sum(x))
print(np.sum(y))

10
26


In [44]:
# sum based on column wise
print(np.sum(x,axis =0))

# sum based on row wise
print(np.sum(x,axis=1))

[4 6]
[3 7]
